
return { 
    ["Wooden Cow"] = {},
    ["Pegasus"] = {},
    ["Minotaur"] = {},
    ["Titan"] = {},
    ["Zeus"] = {},
    ["Ares"] = {},
    ["Medusa"] = {},
    ["Cyclops"] = {},
    ["Poseidon"] = {},
    ["Artemis"] = {},
    ["Hera"] = {},
    ["Demeter"] = {},
    ["Hades"] = {},
    ["Heracles"] = {},
    ["Dionysus"] = {},
    ["Hermes"] = {},
    ["Hydra"] = {},
    ["Ship of Theseus"] = {},
    ["Sword of Damocles"] = {},
    ["Midas"] = {},
    ["Aphrodite"] = {},
    ["Athena"] = {},
    ["Apollo"] = {},
    ["Hephaestus"] = {},
    ["Persephone"] = {},
    ["Prometheus"] = {},
    ["Pandora"] = {},
    ["Icarus"] = {},
    ["Iris"] = {},
    ["Nyx"] = {},
    ["Atlas"] = {},
    ["Daedalus"] = {},
    ["Helios"] = {},
    ["Mnemosyne"] = {},
}
