
return { 
    ["Wooden Cow"] =        { id = 0,  cost = 1, power = 1,  text = "No additional effect.", ability = {}},
    ["Pegasus"] =           { id = 1,  cost = 3, power = 5,  text = "No additional effect.", ability = {}},
    ["Minotaur"] =          { id = 2,  cost = 5, power = 9,  text = "No additional effect.", ability = {}},
    ["Titan"] =             { id = 3,  cost = 6, power = 12, text = "No additional effect.", ability = {}},
    ["Zeus"] =              { id = 4,  cost = 6, power = 11, text = "When Revealed: Lower the power of each card in your opponent's hand by 1.", ability = {}},
    ["Ares"] =              { id = 5,  cost = 4, power = 7,  text = "When Revealed: Gain +2 power for each enemy card here.", ability = {}},
    ["Medusa"] =            { id = 6,  cost = 2, power = 4,  text = "When ANY other card is played here, lower that card's power by 1.", ability = {}},
    ["Cyclops"] =           { id = 7,  cost = 2, power = 5,  text = "When Revealed: Discard your other cards here, gain +2 power for each discarded.", ability = {}},
    ["Poseidon"] =          { id = 8,  cost = 5, power = 9,  text = "When Revealed: Move away an enemy card here with the lowest power.", ability = {}},
    ["Artemis"] =           { id = 9,  cost = 2, power = 3,  text = "When Revealed: Gain +5 power if there is exactly one enemy card here.", ability = {}},
    ["Hera"] =              { id = 10, cost = 4, power = 7,  text = "When Revealed: Give cards in your hand +1 power.", ability = {}},
    ["Demeter"] =           { id = 11, cost = 3, power = 5,  text = "When Revealed: Both players draw a card.", ability = {}},
    ["Hades"] =             { id = 12, cost = 6, power = 6,  text = "When Revealed: Gain +2 power for each card in your discard pile.", ability = {}},
    ["Heracles"] =          { id = 13, cost = 3, power = 6,  text = "When Revealed: Doubles its power if its the strongest card here.", ability = {}},
    ["Dionysus"] =          { id = 14, cost = 4, power = 8,  text = "When Revealed: Gain +2 power for each of your other cards here.", ability = {}},
    ["Hermes"] =            { id = 15, cost = 2, power = 5,  text = "When Revealed: Moves to another location.", ability = {}},
    ["Hydra"] =             { id = 16, cost = 2, power = 3,  text = "Add two copies to your hand when this card is discarded.", ability = {}},
    ["Ship of Theseus"] =   { id = 17, cost = 2, power = 3,  text = "When Revealed: Add a copy with +1 power to your hand.", ability = {}},
    ["Sword of Damocles"] = { id = 18, cost = 1, power = 4,  text = "End of Turn: Loses 1 power if not winning this location.", ability = {}},
    ["Midas"] =             { id = 19, cost = 2, power = 2,  text = "When Revealed: Set ALL cards here to 3 power.", ability = {}},
    ["Aphrodite"] =         { id = 20, cost = 2, power = 4,  text = "When Revealed: Lower the power of each enemy card here by 1.", ability = {}},
    ["Athena"] =            { id = 21, cost = 4, power = 7,  text = "Gain +1 power when you play another card here.", ability = {}},
    ["Apollo"] =            { id = 22, cost = 3, power = 4,  text = "When Revealed: Gain +1 mana next turn.", ability = {}},
    ["Hephaestus"] =        { id = 23, cost = 4, power = 6,  text = "When Revealed: Lower the cost of 2 cards in your hand by 1.", ability = {}},
    ["Persephone"] =        { id = 24, cost = 3, power = 6,  text = "When Revealed: Discard the lowest power card in your hand.", ability = {}},
    ["Prometheus"] =        { id = 25, cost = 4, power = 7,  text = "When Revealed: Draw a card from your opponent's deck.", ability = {}},
    ["Pandora"] =           { id = 26, cost = 2, power = 6,  text = "When Revealed: If no ally cards are here, lower this card's power by 5.", ability = {}},
    ["Icarus"] =            { id = 27, cost = 1, power = 1,  text = "End of Turn: Gains +1 power, but is discarded when its power is greater than 7.", ability = {}},
    ["Iris"] =              { id = 28, cost = 5, power = 1,  text = "End of Turn: Give your cards at each other location +1 power if they have unique powers.", ability = {}},
    ["Nyx"] =               { id = 29, cost = 5, power = 5,  text = "When Revealed: Discards your other cards here, add their power to this card.", ability = {}},
    ["Atlas"] =             { id = 30, cost = 4, power = 8,  text = "End of Turn: Loses 1 power if your side of this location is full.", ability = {}},
    ["Daedalus"] =          { id = 31, cost = 2, power = 4,  text = "When Revealed: Add a Wooden Cow to each other location.", ability = {}},
    ["Helios"] =            { id = 32, cost = 4, power = 8,  text = "End of Turn: Discard this.", ability = {}},
    ["Mnemosyne"] =         { id = 33, cost = 3, power = 6,  text = "When Revealed: Add a copy of the last card you played to your hand.", ability = {}},
}
